[project]
name = "techjam-conversational-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Wenn Yu", email = "chuawennyu@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.2",
    "sentence-transformers>=6.0.0",
]

[project.scripts]
techjam-conversational-search = "techjam_conversational_search:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
